version: '3.7'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - /opt/webapp/nginx.conf:/etc/nginx/nginx.conf
      - ./app:/var/www/html
    depends_on:
      - php

  php:
    build: .
    volumes:
      - ./app:/var/www/html

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webapp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
